# Generated by Django 2.2.7 on 2019-11-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbankdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_id',
            field=models.BigIntegerField(max_length=50),
        ),
    ]
