# Generated by Django 2.2.7 on 2019-11-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbankdetails', '0002_auto_20191120_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
