# Generated by Django 2.2.7 on 2019-11-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbankdetails', '0003_bank_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_id',
            field=models.IntegerField(max_length=50),
        ),
    ]
